name: STM32 Regression

on: [workflow_dispatch]

jobs:
  checkout-common:
    name: Checkout Common Repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          ubuntu-latest
        ]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout Common Repository
        uses: actions/checkout@v2

        with:
          submodules: true

  checkout-project:
    name: Checkout Project Repositories
    runs-on: ubuntu-latest
    needs: checkout-common
    strategy:
      matrix:
        project: [
          # stm32f1-bluepill,
          # stm32l4-nucleo32,
          # stm32f4-nucleo64,
          stm32f4-minimal
        ]

    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v2

        with:
          repository: PhischDotOrg/${{ matrix.project }}
          path: src-${{ matrix.project }}

      - name: Link to Common Repository
        working-directory: src-${{ matrix.project }}

        run: ln -s $GITHUB_WORKSPACE common

      - name: CMake Configure
        # run: cmake -S src-${{ matrix.project }} -B build-${{ matrix.project }} -DUNITTEST=true
        run: |
          ls -l
          ls -l src-${{ matrix.project }}
          ls -l src-${{ matrix.project }}/common
          ls -l src-${{ matrix.project }}/common/

