name: STM32 Regression

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        project: [
          stm32f1-bluepill,
          stm32l4-nucleo32,
          stm32f4-nucleo64,
          stm32f4-minimal
        ]
        # build_type: [ Release, RelWithDebInfo, MinSizeRel, Debug ]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout Repositories
        uses: actions/checkout@v2
        working-directory: ${{runner.workspace}}

        with:
          repository: PhischDotOrg/${{ matrix.project }}
          path: src-${{ matrix.project }}

      - name: CMake Configure
        working-directory: ${{runner.workspace}}/src-${{ matrix.project }}

        run: git describe --always --dirty=+
